# Uncomment the next line to define a global platform for your project

platform :ios, '13.0'
inhibit_all_warnings!

target 'Pitaya' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Pitaya
  pod 'SnapKit'
  pod 'Masonry'

  target 'PitayaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PitayaUITests' do
    # Pods for testing
  end

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
#        puts "==============target #{target} #{config.name}"
#        puts JSON.pretty_generate(JSON.parse(config.build_settings.to_json))
        if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 11.0
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
        end
      end
    end
  end

end
